language: python
python:
  - "2.7"
install:
  - "pip install coveralls"
  - "make install"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "make test"
  - "./scripts/i18n.sh eo > /dev/null"
after_success:
  coveralls
